# Generated by Django 2.2.15 on 2021-01-26 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cookie_consent", "0002_auto__add_logitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthenticatedUserCookieConsent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.IntegerField(
                        choices=[(-1, "Declined"), (1, "Accepted")],
                        verbose_name="Action",
                    ),
                ),
                ("version", models.CharField(max_length=32, verbose_name="Version")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "cookiegroup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cookie_consent.CookieGroup",
                        verbose_name="Cookie Group",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User cookie consent",
                "verbose_name_plural": "User cookie consents",
                "ordering": ["-created"],
                "unique_together": {("user", "cookiegroup")},
            },
        ),
    ]
